#!/usr/bin/env python3
"""Generate nx_gles_gen.c: ES2 passthrough + ES3 logged stubs.

Reads system GLES2/gl2.h and GLES3/gl3.h. Functions present in gl2.h are
forwarded to the real Mali libGLESv2. Functions only in gl3.h get a
log-once stub. Names listed in overrides.txt are skipped entirely (they
live hand-written in nx_gles3_core.c).
"""
import re, sys, os

PROTO = re.compile(r'GL_APICALL\s+(.+?)\s*GL_APIENTRY\s+(gl\w+)\s*\((.*?)\);', re.S)

def parse(path):
    out = {}
    src = open(path).read()
    for ret, name, args in PROTO.findall(src):
        args = ' '.join(args.split())
        out[name] = (ret.strip(), args)
    return out

def argnames(args):
    if args.strip() in ('void', ''):
        return ''
    names = []
    for a in args.split(','):
        a = a.strip()
        # drop array suffix
        a = re.sub(r'\[\d*\]$', '', a)
        m = re.search(r'([A-Za-z_]\w*)$', a)
        names.append(m.group(1))
    return ', '.join(names)

def main():
    es2 = parse('/usr/include/GLES2/gl2.h')
    es3 = parse('/usr/include/GLES3/gl3.h')
    skip = set()
    if os.path.exists(sys.argv[1]):
        skip = {l.strip() for l in open(sys.argv[1]) if l.strip() and not l.startswith('#')}
    w = open(sys.argv[2], 'w')
    w.write('/* GENERATED by gen_shim.py — do not edit. */\n')
    w.write('#include "nx_shim.h"\n\n')
    for name in sorted(es3):
        if name in skip:
            continue
        ret, args = es3[name]
        an = argnames(args)
        arglist = '(void)' if args.strip() in ('void','') else '(%s)' % args
        if name in es2:
            # passthrough
            w.write('GL_APICALL %s GL_APIENTRY %s%s {\n' % (ret, name, arglist))
            w.write('    static %s (*fn)(%s);\n' % (ret, args))
            w.write('    if (!fn) fn = nx_mali_sym("%s");\n' % name)
            if ret.strip() == 'void':
                w.write('    fn(%s);\n' % an)
            else:
                w.write('    return fn(%s);\n' % an)
            w.write('}\n')
        else:
            # ES3-only stub
            w.write('GL_APICALL %s GL_APIENTRY %s%s {\n' % (ret, name, arglist))
            w.write('    NX_STUB_LOG("%s");\n' % name)
            for a in ([] if args.strip() in ('void','') else args.split(',')):
                m = re.search(r'([A-Za-z_]\w*)$', re.sub(r'\[\d*\]$','',a.strip()))
                w.write('    (void)%s;\n' % m.group(1))
            if ret.strip() != 'void':
                w.write('    return (%s)0;\n' % ret)
            w.write('}\n')
    w.close()
    print('es2=%d es3only=%d skipped=%d' % (
        len([n for n in es3 if n in es2 and n not in skip]),
        len([n for n in es3 if n not in es2 and n not in skip]),
        len(skip)))

main()
