/* GENERATED by gen_shim.py — do not edit. */
#include "nx_shim.h"

GL_APICALL void GL_APIENTRY glActiveTexture(GLenum texture) {
    static void (*fn)(GLenum texture);
    if (!fn) fn = nx_mali_sym("glActiveTexture");
    fn(texture);
}
GL_APICALL void GL_APIENTRY glAttachShader(GLuint program, GLuint shader) {
    static void (*fn)(GLuint program, GLuint shader);
    if (!fn) fn = nx_mali_sym("glAttachShader");
    fn(program, shader);
}
GL_APICALL void GL_APIENTRY glBeginQuery(GLenum target, GLuint id) {
    NX_STUB_LOG("glBeginQuery");
    (void)target;
    (void)id;
}
GL_APICALL void GL_APIENTRY glBeginTransformFeedback(GLenum primitiveMode) {
    NX_STUB_LOG("glBeginTransformFeedback");
    (void)primitiveMode;
}
GL_APICALL void GL_APIENTRY glBindAttribLocation(GLuint program, GLuint index, const GLchar *name) {
    static void (*fn)(GLuint program, GLuint index, const GLchar *name);
    if (!fn) fn = nx_mali_sym("glBindAttribLocation");
    fn(program, index, name);
}
GL_APICALL void GL_APIENTRY glBindRenderbuffer(GLenum target, GLuint renderbuffer) {
    static void (*fn)(GLenum target, GLuint renderbuffer);
    if (!fn) fn = nx_mali_sym("glBindRenderbuffer");
    fn(target, renderbuffer);
}
GL_APICALL void GL_APIENTRY glBindTransformFeedback(GLenum target, GLuint id) {
    NX_STUB_LOG("glBindTransformFeedback");
    (void)target;
    (void)id;
}
GL_APICALL void GL_APIENTRY glBlendColor(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha) {
    static void (*fn)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
    if (!fn) fn = nx_mali_sym("glBlendColor");
    fn(red, green, blue, alpha);
}
GL_APICALL void GL_APIENTRY glBlendEquation(GLenum mode) {
    static void (*fn)(GLenum mode);
    if (!fn) fn = nx_mali_sym("glBlendEquation");
    fn(mode);
}
GL_APICALL void GL_APIENTRY glBlendEquationSeparate(GLenum modeRGB, GLenum modeAlpha) {
    static void (*fn)(GLenum modeRGB, GLenum modeAlpha);
    if (!fn) fn = nx_mali_sym("glBlendEquationSeparate");
    fn(modeRGB, modeAlpha);
}
GL_APICALL void GL_APIENTRY glBlendFunc(GLenum sfactor, GLenum dfactor) {
    static void (*fn)(GLenum sfactor, GLenum dfactor);
    if (!fn) fn = nx_mali_sym("glBlendFunc");
    fn(sfactor, dfactor);
}
GL_APICALL void GL_APIENTRY glBlendFuncSeparate(GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha) {
    static void (*fn)(GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha);
    if (!fn) fn = nx_mali_sym("glBlendFuncSeparate");
    fn(sfactorRGB, dfactorRGB, sfactorAlpha, dfactorAlpha);
}
GL_APICALL GLenum GL_APIENTRY glCheckFramebufferStatus(GLenum target) {
    static GLenum (*fn)(GLenum target);
    if (!fn) fn = nx_mali_sym("glCheckFramebufferStatus");
    return fn(target);
}
GL_APICALL void GL_APIENTRY glClearBufferfi(GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil) {
    NX_STUB_LOG("glClearBufferfi");
    (void)buffer;
    (void)drawbuffer;
    (void)depth;
    (void)stencil;
}
GL_APICALL void GL_APIENTRY glClearBufferfv(GLenum buffer, GLint drawbuffer, const GLfloat *value) {
    NX_STUB_LOG("glClearBufferfv");
    (void)buffer;
    (void)drawbuffer;
    (void)value;
}
GL_APICALL void GL_APIENTRY glClearBufferiv(GLenum buffer, GLint drawbuffer, const GLint *value) {
    NX_STUB_LOG("glClearBufferiv");
    (void)buffer;
    (void)drawbuffer;
    (void)value;
}
GL_APICALL void GL_APIENTRY glClearBufferuiv(GLenum buffer, GLint drawbuffer, const GLuint *value) {
    NX_STUB_LOG("glClearBufferuiv");
    (void)buffer;
    (void)drawbuffer;
    (void)value;
}
GL_APICALL void GL_APIENTRY glClearDepthf(GLfloat d) {
    static void (*fn)(GLfloat d);
    if (!fn) fn = nx_mali_sym("glClearDepthf");
    fn(d);
}
GL_APICALL void GL_APIENTRY glClearStencil(GLint s) {
    static void (*fn)(GLint s);
    if (!fn) fn = nx_mali_sym("glClearStencil");
    fn(s);
}
GL_APICALL void GL_APIENTRY glColorMask(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha) {
    static void (*fn)(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
    if (!fn) fn = nx_mali_sym("glColorMask");
    fn(red, green, blue, alpha);
}
GL_APICALL void GL_APIENTRY glCompressedTexImage2D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void *data) {
    static void (*fn)(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void *data);
    if (!fn) fn = nx_mali_sym("glCompressedTexImage2D");
    fn(target, level, internalformat, width, height, border, imageSize, data);
}
GL_APICALL void GL_APIENTRY glCompressedTexImage3D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const void *data) {
    NX_STUB_LOG("glCompressedTexImage3D");
    (void)target;
    (void)level;
    (void)internalformat;
    (void)width;
    (void)height;
    (void)depth;
    (void)border;
    (void)imageSize;
    (void)data;
}
GL_APICALL void GL_APIENTRY glCompressedTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void *data) {
    static void (*fn)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void *data);
    if (!fn) fn = nx_mali_sym("glCompressedTexSubImage2D");
    fn(target, level, xoffset, yoffset, width, height, format, imageSize, data);
}
GL_APICALL void GL_APIENTRY glCompressedTexSubImage3D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const void *data) {
    NX_STUB_LOG("glCompressedTexSubImage3D");
    (void)target;
    (void)level;
    (void)xoffset;
    (void)yoffset;
    (void)zoffset;
    (void)width;
    (void)height;
    (void)depth;
    (void)format;
    (void)imageSize;
    (void)data;
}
GL_APICALL void GL_APIENTRY glCopyTexImage2D(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border) {
    static void (*fn)(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
    if (!fn) fn = nx_mali_sym("glCopyTexImage2D");
    fn(target, level, internalformat, x, y, width, height, border);
}
GL_APICALL void GL_APIENTRY glCopyTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height) {
    static void (*fn)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
    if (!fn) fn = nx_mali_sym("glCopyTexSubImage2D");
    fn(target, level, xoffset, yoffset, x, y, width, height);
}
GL_APICALL void GL_APIENTRY glCopyTexSubImage3D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height) {
    NX_STUB_LOG("glCopyTexSubImage3D");
    (void)target;
    (void)level;
    (void)xoffset;
    (void)yoffset;
    (void)zoffset;
    (void)x;
    (void)y;
    (void)width;
    (void)height;
}
GL_APICALL GLuint GL_APIENTRY glCreateProgram(void) {
    static GLuint (*fn)(void);
    if (!fn) fn = nx_mali_sym("glCreateProgram");
    return fn();
}
GL_APICALL GLuint GL_APIENTRY glCreateShader(GLenum type) {
    static GLuint (*fn)(GLenum type);
    if (!fn) fn = nx_mali_sym("glCreateShader");
    return fn(type);
}
GL_APICALL void GL_APIENTRY glCullFace(GLenum mode) {
    static void (*fn)(GLenum mode);
    if (!fn) fn = nx_mali_sym("glCullFace");
    fn(mode);
}
GL_APICALL void GL_APIENTRY glDeleteProgram(GLuint program) {
    static void (*fn)(GLuint program);
    if (!fn) fn = nx_mali_sym("glDeleteProgram");
    fn(program);
}
GL_APICALL void GL_APIENTRY glDeleteQueries(GLsizei n, const GLuint *ids) {
    NX_STUB_LOG("glDeleteQueries");
    (void)n;
    (void)ids;
}
GL_APICALL void GL_APIENTRY glDeleteRenderbuffers(GLsizei n, const GLuint *renderbuffers) {
    static void (*fn)(GLsizei n, const GLuint *renderbuffers);
    if (!fn) fn = nx_mali_sym("glDeleteRenderbuffers");
    fn(n, renderbuffers);
}
GL_APICALL void GL_APIENTRY glDeleteShader(GLuint shader) {
    static void (*fn)(GLuint shader);
    if (!fn) fn = nx_mali_sym("glDeleteShader");
    fn(shader);
}
GL_APICALL void GL_APIENTRY glDeleteTextures(GLsizei n, const GLuint *textures) {
    static void (*fn)(GLsizei n, const GLuint *textures);
    if (!fn) fn = nx_mali_sym("glDeleteTextures");
    fn(n, textures);
}
GL_APICALL void GL_APIENTRY glDeleteTransformFeedbacks(GLsizei n, const GLuint *ids) {
    NX_STUB_LOG("glDeleteTransformFeedbacks");
    (void)n;
    (void)ids;
}
GL_APICALL void GL_APIENTRY glDepthFunc(GLenum func) {
    static void (*fn)(GLenum func);
    if (!fn) fn = nx_mali_sym("glDepthFunc");
    fn(func);
}
GL_APICALL void GL_APIENTRY glDepthMask(GLboolean flag) {
    static void (*fn)(GLboolean flag);
    if (!fn) fn = nx_mali_sym("glDepthMask");
    fn(flag);
}
GL_APICALL void GL_APIENTRY glDepthRangef(GLfloat n, GLfloat f) {
    static void (*fn)(GLfloat n, GLfloat f);
    if (!fn) fn = nx_mali_sym("glDepthRangef");
    fn(n, f);
}
GL_APICALL void GL_APIENTRY glDetachShader(GLuint program, GLuint shader) {
    static void (*fn)(GLuint program, GLuint shader);
    if (!fn) fn = nx_mali_sym("glDetachShader");
    fn(program, shader);
}
GL_APICALL void GL_APIENTRY glDrawRangeElements(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void *indices) {
    NX_STUB_LOG("glDrawRangeElements");
    (void)mode;
    (void)start;
    (void)end;
    (void)count;
    (void)type;
    (void)indices;
}
GL_APICALL void GL_APIENTRY glEndQuery(GLenum target) {
    NX_STUB_LOG("glEndQuery");
    (void)target;
}
GL_APICALL void GL_APIENTRY glEndTransformFeedback(void) {
    NX_STUB_LOG("glEndTransformFeedback");
}
GL_APICALL void GL_APIENTRY glFinish(void) {
    static void (*fn)(void);
    if (!fn) fn = nx_mali_sym("glFinish");
    fn();
}
GL_APICALL void GL_APIENTRY glFlush(void) {
    static void (*fn)(void);
    if (!fn) fn = nx_mali_sym("glFlush");
    fn();
}
GL_APICALL void GL_APIENTRY glFramebufferRenderbuffer(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer) {
    static void (*fn)(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
    if (!fn) fn = nx_mali_sym("glFramebufferRenderbuffer");
    fn(target, attachment, renderbuffertarget, renderbuffer);
}
GL_APICALL void GL_APIENTRY glFramebufferTextureLayer(GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer) {
    NX_STUB_LOG("glFramebufferTextureLayer");
    (void)target;
    (void)attachment;
    (void)texture;
    (void)level;
    (void)layer;
}
GL_APICALL void GL_APIENTRY glFrontFace(GLenum mode) {
    static void (*fn)(GLenum mode);
    if (!fn) fn = nx_mali_sym("glFrontFace");
    fn(mode);
}
GL_APICALL void GL_APIENTRY glGenBuffers(GLsizei n, GLuint *buffers) {
    static void (*fn)(GLsizei n, GLuint *buffers);
    if (!fn) fn = nx_mali_sym("glGenBuffers");
    fn(n, buffers);
}
GL_APICALL void GL_APIENTRY glGenFramebuffers(GLsizei n, GLuint *framebuffers) {
    static void (*fn)(GLsizei n, GLuint *framebuffers);
    if (!fn) fn = nx_mali_sym("glGenFramebuffers");
    fn(n, framebuffers);
}
GL_APICALL void GL_APIENTRY glGenQueries(GLsizei n, GLuint *ids) {
    NX_STUB_LOG("glGenQueries");
    (void)n;
    (void)ids;
}
GL_APICALL void GL_APIENTRY glGenRenderbuffers(GLsizei n, GLuint *renderbuffers) {
    static void (*fn)(GLsizei n, GLuint *renderbuffers);
    if (!fn) fn = nx_mali_sym("glGenRenderbuffers");
    fn(n, renderbuffers);
}
GL_APICALL void GL_APIENTRY glGenTextures(GLsizei n, GLuint *textures) {
    static void (*fn)(GLsizei n, GLuint *textures);
    if (!fn) fn = nx_mali_sym("glGenTextures");
    fn(n, textures);
}
GL_APICALL void GL_APIENTRY glGenTransformFeedbacks(GLsizei n, GLuint *ids) {
    NX_STUB_LOG("glGenTransformFeedbacks");
    (void)n;
    (void)ids;
}
GL_APICALL void GL_APIENTRY glGetActiveAttrib(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name) {
    static void (*fn)(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name);
    if (!fn) fn = nx_mali_sym("glGetActiveAttrib");
    fn(program, index, bufSize, length, size, type, name);
}
GL_APICALL void GL_APIENTRY glGetActiveUniform(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name) {
    static void (*fn)(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name);
    if (!fn) fn = nx_mali_sym("glGetActiveUniform");
    fn(program, index, bufSize, length, size, type, name);
}
GL_APICALL void GL_APIENTRY glGetAttachedShaders(GLuint program, GLsizei maxCount, GLsizei *count, GLuint *shaders) {
    static void (*fn)(GLuint program, GLsizei maxCount, GLsizei *count, GLuint *shaders);
    if (!fn) fn = nx_mali_sym("glGetAttachedShaders");
    fn(program, maxCount, count, shaders);
}
GL_APICALL GLint GL_APIENTRY glGetAttribLocation(GLuint program, const GLchar *name) {
    static GLint (*fn)(GLuint program, const GLchar *name);
    if (!fn) fn = nx_mali_sym("glGetAttribLocation");
    return fn(program, name);
}
GL_APICALL void GL_APIENTRY glGetBooleanv(GLenum pname, GLboolean *data) {
    static void (*fn)(GLenum pname, GLboolean *data);
    if (!fn) fn = nx_mali_sym("glGetBooleanv");
    fn(pname, data);
}
GL_APICALL void GL_APIENTRY glGetBufferParameteri64v(GLenum target, GLenum pname, GLint64 *params) {
    NX_STUB_LOG("glGetBufferParameteri64v");
    (void)target;
    (void)pname;
    (void)params;
}
GL_APICALL void GL_APIENTRY glGetBufferParameteriv(GLenum target, GLenum pname, GLint *params) {
    static void (*fn)(GLenum target, GLenum pname, GLint *params);
    if (!fn) fn = nx_mali_sym("glGetBufferParameteriv");
    fn(target, pname, params);
}
GL_APICALL void GL_APIENTRY glGetBufferPointerv(GLenum target, GLenum pname, void **params) {
    NX_STUB_LOG("glGetBufferPointerv");
    (void)target;
    (void)pname;
    (void)params;
}
GL_APICALL void GL_APIENTRY glGetFloatv(GLenum pname, GLfloat *data) {
    static void (*fn)(GLenum pname, GLfloat *data);
    if (!fn) fn = nx_mali_sym("glGetFloatv");
    fn(pname, data);
}
GL_APICALL GLint GL_APIENTRY glGetFragDataLocation(GLuint program, const GLchar *name) {
    NX_STUB_LOG("glGetFragDataLocation");
    (void)program;
    (void)name;
    return (GLint)0;
}
GL_APICALL void GL_APIENTRY glGetInteger64i_v(GLenum target, GLuint index, GLint64 *data) {
    NX_STUB_LOG("glGetInteger64i_v");
    (void)target;
    (void)index;
    (void)data;
}
GL_APICALL void GL_APIENTRY glGetIntegeri_v(GLenum target, GLuint index, GLint *data) {
    NX_STUB_LOG("glGetIntegeri_v");
    (void)target;
    (void)index;
    (void)data;
}
GL_APICALL void GL_APIENTRY glGetInternalformativ(GLenum target, GLenum internalformat, GLenum pname, GLsizei count, GLint *params) {
    NX_STUB_LOG("glGetInternalformativ");
    (void)target;
    (void)internalformat;
    (void)pname;
    (void)count;
    (void)params;
}
GL_APICALL void GL_APIENTRY glGetProgramBinary(GLuint program, GLsizei bufSize, GLsizei *length, GLenum *binaryFormat, void *binary) {
    NX_STUB_LOG("glGetProgramBinary");
    (void)program;
    (void)bufSize;
    (void)length;
    (void)binaryFormat;
    (void)binary;
}
GL_APICALL void GL_APIENTRY glGetQueryObjectuiv(GLuint id, GLenum pname, GLuint *params) {
    NX_STUB_LOG("glGetQueryObjectuiv");
    (void)id;
    (void)pname;
    (void)params;
}
GL_APICALL void GL_APIENTRY glGetQueryiv(GLenum target, GLenum pname, GLint *params) {
    NX_STUB_LOG("glGetQueryiv");
    (void)target;
    (void)pname;
    (void)params;
}
GL_APICALL void GL_APIENTRY glGetRenderbufferParameteriv(GLenum target, GLenum pname, GLint *params) {
    static void (*fn)(GLenum target, GLenum pname, GLint *params);
    if (!fn) fn = nx_mali_sym("glGetRenderbufferParameteriv");
    fn(target, pname, params);
}
GL_APICALL void GL_APIENTRY glGetShaderPrecisionFormat(GLenum shadertype, GLenum precisiontype, GLint *range, GLint *precision) {
    static void (*fn)(GLenum shadertype, GLenum precisiontype, GLint *range, GLint *precision);
    if (!fn) fn = nx_mali_sym("glGetShaderPrecisionFormat");
    fn(shadertype, precisiontype, range, precision);
}
GL_APICALL void GL_APIENTRY glGetShaderSource(GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *source) {
    static void (*fn)(GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *source);
    if (!fn) fn = nx_mali_sym("glGetShaderSource");
    fn(shader, bufSize, length, source);
}
GL_APICALL void GL_APIENTRY glGetTexParameterfv(GLenum target, GLenum pname, GLfloat *params) {
    static void (*fn)(GLenum target, GLenum pname, GLfloat *params);
    if (!fn) fn = nx_mali_sym("glGetTexParameterfv");
    fn(target, pname, params);
}
GL_APICALL void GL_APIENTRY glGetTexParameteriv(GLenum target, GLenum pname, GLint *params) {
    static void (*fn)(GLenum target, GLenum pname, GLint *params);
    if (!fn) fn = nx_mali_sym("glGetTexParameteriv");
    fn(target, pname, params);
}
GL_APICALL void GL_APIENTRY glGetTransformFeedbackVarying(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLsizei *size, GLenum *type, GLchar *name) {
    NX_STUB_LOG("glGetTransformFeedbackVarying");
    (void)program;
    (void)index;
    (void)bufSize;
    (void)length;
    (void)size;
    (void)type;
    (void)name;
}
GL_APICALL void GL_APIENTRY glGetUniformfv(GLuint program, GLint location, GLfloat *params) {
    static void (*fn)(GLuint program, GLint location, GLfloat *params);
    if (!fn) fn = nx_mali_sym("glGetUniformfv");
    fn(program, location, params);
}
GL_APICALL void GL_APIENTRY glGetUniformiv(GLuint program, GLint location, GLint *params) {
    static void (*fn)(GLuint program, GLint location, GLint *params);
    if (!fn) fn = nx_mali_sym("glGetUniformiv");
    fn(program, location, params);
}
GL_APICALL void GL_APIENTRY glGetUniformuiv(GLuint program, GLint location, GLuint *params) {
    NX_STUB_LOG("glGetUniformuiv");
    (void)program;
    (void)location;
    (void)params;
}
GL_APICALL void GL_APIENTRY glGetVertexAttribIiv(GLuint index, GLenum pname, GLint *params) {
    NX_STUB_LOG("glGetVertexAttribIiv");
    (void)index;
    (void)pname;
    (void)params;
}
GL_APICALL void GL_APIENTRY glGetVertexAttribIuiv(GLuint index, GLenum pname, GLuint *params) {
    NX_STUB_LOG("glGetVertexAttribIuiv");
    (void)index;
    (void)pname;
    (void)params;
}
GL_APICALL void GL_APIENTRY glGetVertexAttribPointerv(GLuint index, GLenum pname, void **pointer) {
    static void (*fn)(GLuint index, GLenum pname, void **pointer);
    if (!fn) fn = nx_mali_sym("glGetVertexAttribPointerv");
    fn(index, pname, pointer);
}
GL_APICALL void GL_APIENTRY glGetVertexAttribfv(GLuint index, GLenum pname, GLfloat *params) {
    static void (*fn)(GLuint index, GLenum pname, GLfloat *params);
    if (!fn) fn = nx_mali_sym("glGetVertexAttribfv");
    fn(index, pname, params);
}
GL_APICALL void GL_APIENTRY glGetVertexAttribiv(GLuint index, GLenum pname, GLint *params) {
    static void (*fn)(GLuint index, GLenum pname, GLint *params);
    if (!fn) fn = nx_mali_sym("glGetVertexAttribiv");
    fn(index, pname, params);
}
GL_APICALL void GL_APIENTRY glHint(GLenum target, GLenum mode) {
    static void (*fn)(GLenum target, GLenum mode);
    if (!fn) fn = nx_mali_sym("glHint");
    fn(target, mode);
}
GL_APICALL GLboolean GL_APIENTRY glIsBuffer(GLuint buffer) {
    static GLboolean (*fn)(GLuint buffer);
    if (!fn) fn = nx_mali_sym("glIsBuffer");
    return fn(buffer);
}
GL_APICALL GLboolean GL_APIENTRY glIsEnabled(GLenum cap) {
    static GLboolean (*fn)(GLenum cap);
    if (!fn) fn = nx_mali_sym("glIsEnabled");
    return fn(cap);
}
GL_APICALL GLboolean GL_APIENTRY glIsFramebuffer(GLuint framebuffer) {
    static GLboolean (*fn)(GLuint framebuffer);
    if (!fn) fn = nx_mali_sym("glIsFramebuffer");
    return fn(framebuffer);
}
GL_APICALL GLboolean GL_APIENTRY glIsProgram(GLuint program) {
    static GLboolean (*fn)(GLuint program);
    if (!fn) fn = nx_mali_sym("glIsProgram");
    return fn(program);
}
GL_APICALL GLboolean GL_APIENTRY glIsQuery(GLuint id) {
    NX_STUB_LOG("glIsQuery");
    (void)id;
    return (GLboolean)0;
}
GL_APICALL GLboolean GL_APIENTRY glIsRenderbuffer(GLuint renderbuffer) {
    static GLboolean (*fn)(GLuint renderbuffer);
    if (!fn) fn = nx_mali_sym("glIsRenderbuffer");
    return fn(renderbuffer);
}
GL_APICALL GLboolean GL_APIENTRY glIsShader(GLuint shader) {
    static GLboolean (*fn)(GLuint shader);
    if (!fn) fn = nx_mali_sym("glIsShader");
    return fn(shader);
}
GL_APICALL GLboolean GL_APIENTRY glIsTexture(GLuint texture) {
    static GLboolean (*fn)(GLuint texture);
    if (!fn) fn = nx_mali_sym("glIsTexture");
    return fn(texture);
}
GL_APICALL GLboolean GL_APIENTRY glIsTransformFeedback(GLuint id) {
    NX_STUB_LOG("glIsTransformFeedback");
    (void)id;
    return (GLboolean)0;
}
GL_APICALL void GL_APIENTRY glLineWidth(GLfloat width) {
    static void (*fn)(GLfloat width);
    if (!fn) fn = nx_mali_sym("glLineWidth");
    fn(width);
}
GL_APICALL void GL_APIENTRY glPauseTransformFeedback(void) {
    NX_STUB_LOG("glPauseTransformFeedback");
}
GL_APICALL void GL_APIENTRY glPixelStorei(GLenum pname, GLint param) {
    static void (*fn)(GLenum pname, GLint param);
    if (!fn) fn = nx_mali_sym("glPixelStorei");
    fn(pname, param);
}
GL_APICALL void GL_APIENTRY glPolygonOffset(GLfloat factor, GLfloat units) {
    static void (*fn)(GLfloat factor, GLfloat units);
    if (!fn) fn = nx_mali_sym("glPolygonOffset");
    fn(factor, units);
}
GL_APICALL void GL_APIENTRY glProgramBinary(GLuint program, GLenum binaryFormat, const void *binary, GLsizei length) {
    NX_STUB_LOG("glProgramBinary");
    (void)program;
    (void)binaryFormat;
    (void)binary;
    (void)length;
}
GL_APICALL void GL_APIENTRY glProgramParameteri(GLuint program, GLenum pname, GLint value) {
    NX_STUB_LOG("glProgramParameteri");
    (void)program;
    (void)pname;
    (void)value;
}
GL_APICALL void GL_APIENTRY glReadPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void *pixels) {
    static void (*fn)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void *pixels);
    if (!fn) fn = nx_mali_sym("glReadPixels");
    fn(x, y, width, height, format, type, pixels);
}
GL_APICALL void GL_APIENTRY glReleaseShaderCompiler(void) {
    static void (*fn)(void);
    if (!fn) fn = nx_mali_sym("glReleaseShaderCompiler");
    fn();
}
GL_APICALL void GL_APIENTRY glRenderbufferStorageMultisample(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height) {
    NX_STUB_LOG("glRenderbufferStorageMultisample");
    (void)target;
    (void)samples;
    (void)internalformat;
    (void)width;
    (void)height;
}
GL_APICALL void GL_APIENTRY glResumeTransformFeedback(void) {
    NX_STUB_LOG("glResumeTransformFeedback");
}
GL_APICALL void GL_APIENTRY glSampleCoverage(GLfloat value, GLboolean invert) {
    static void (*fn)(GLfloat value, GLboolean invert);
    if (!fn) fn = nx_mali_sym("glSampleCoverage");
    fn(value, invert);
}
GL_APICALL void GL_APIENTRY glScissor(GLint x, GLint y, GLsizei width, GLsizei height) {
    static void (*fn)(GLint x, GLint y, GLsizei width, GLsizei height);
    if (!fn) fn = nx_mali_sym("glScissor");
    fn(x, y, width, height);
}
GL_APICALL void GL_APIENTRY glShaderBinary(GLsizei count, const GLuint *shaders, GLenum binaryFormat, const void *binary, GLsizei length) {
    static void (*fn)(GLsizei count, const GLuint *shaders, GLenum binaryFormat, const void *binary, GLsizei length);
    if (!fn) fn = nx_mali_sym("glShaderBinary");
    fn(count, shaders, binaryFormat, binary, length);
}
GL_APICALL void GL_APIENTRY glStencilFunc(GLenum func, GLint ref, GLuint mask) {
    static void (*fn)(GLenum func, GLint ref, GLuint mask);
    if (!fn) fn = nx_mali_sym("glStencilFunc");
    fn(func, ref, mask);
}
GL_APICALL void GL_APIENTRY glStencilFuncSeparate(GLenum face, GLenum func, GLint ref, GLuint mask) {
    static void (*fn)(GLenum face, GLenum func, GLint ref, GLuint mask);
    if (!fn) fn = nx_mali_sym("glStencilFuncSeparate");
    fn(face, func, ref, mask);
}
GL_APICALL void GL_APIENTRY glStencilMask(GLuint mask) {
    static void (*fn)(GLuint mask);
    if (!fn) fn = nx_mali_sym("glStencilMask");
    fn(mask);
}
GL_APICALL void GL_APIENTRY glStencilMaskSeparate(GLenum face, GLuint mask) {
    static void (*fn)(GLenum face, GLuint mask);
    if (!fn) fn = nx_mali_sym("glStencilMaskSeparate");
    fn(face, mask);
}
GL_APICALL void GL_APIENTRY glStencilOp(GLenum fail, GLenum zfail, GLenum zpass) {
    static void (*fn)(GLenum fail, GLenum zfail, GLenum zpass);
    if (!fn) fn = nx_mali_sym("glStencilOp");
    fn(fail, zfail, zpass);
}
GL_APICALL void GL_APIENTRY glStencilOpSeparate(GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass) {
    static void (*fn)(GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass);
    if (!fn) fn = nx_mali_sym("glStencilOpSeparate");
    fn(face, sfail, dpfail, dppass);
}
GL_APICALL void GL_APIENTRY glTexParameterfv(GLenum target, GLenum pname, const GLfloat *params) {
    static void (*fn)(GLenum target, GLenum pname, const GLfloat *params);
    if (!fn) fn = nx_mali_sym("glTexParameterfv");
    fn(target, pname, params);
}
GL_APICALL void GL_APIENTRY glTexParameteriv(GLenum target, GLenum pname, const GLint *params) {
    static void (*fn)(GLenum target, GLenum pname, const GLint *params);
    if (!fn) fn = nx_mali_sym("glTexParameteriv");
    fn(target, pname, params);
}
GL_APICALL void GL_APIENTRY glTransformFeedbackVaryings(GLuint program, GLsizei count, const GLchar *const*varyings, GLenum bufferMode) {
    NX_STUB_LOG("glTransformFeedbackVaryings");
    (void)program;
    (void)count;
    (void)varyings;
    (void)bufferMode;
}
GL_APICALL void GL_APIENTRY glUniform1f(GLint location, GLfloat v0) {
    static void (*fn)(GLint location, GLfloat v0);
    if (!fn) fn = nx_mali_sym("glUniform1f");
    fn(location, v0);
}
GL_APICALL void GL_APIENTRY glUniform1fv(GLint location, GLsizei count, const GLfloat *value) {
    static void (*fn)(GLint location, GLsizei count, const GLfloat *value);
    if (!fn) fn = nx_mali_sym("glUniform1fv");
    fn(location, count, value);
}
GL_APICALL void GL_APIENTRY glUniform1i(GLint location, GLint v0) {
    static void (*fn)(GLint location, GLint v0);
    if (!fn) fn = nx_mali_sym("glUniform1i");
    fn(location, v0);
}
GL_APICALL void GL_APIENTRY glUniform1iv(GLint location, GLsizei count, const GLint *value) {
    static void (*fn)(GLint location, GLsizei count, const GLint *value);
    if (!fn) fn = nx_mali_sym("glUniform1iv");
    fn(location, count, value);
}
GL_APICALL void GL_APIENTRY glUniform1ui(GLint location, GLuint v0) {
    NX_STUB_LOG("glUniform1ui");
    (void)location;
    (void)v0;
}
GL_APICALL void GL_APIENTRY glUniform1uiv(GLint location, GLsizei count, const GLuint *value) {
    NX_STUB_LOG("glUniform1uiv");
    (void)location;
    (void)count;
    (void)value;
}
GL_APICALL void GL_APIENTRY glUniform2f(GLint location, GLfloat v0, GLfloat v1) {
    static void (*fn)(GLint location, GLfloat v0, GLfloat v1);
    if (!fn) fn = nx_mali_sym("glUniform2f");
    fn(location, v0, v1);
}
GL_APICALL void GL_APIENTRY glUniform2fv(GLint location, GLsizei count, const GLfloat *value) {
    static void (*fn)(GLint location, GLsizei count, const GLfloat *value);
    if (!fn) fn = nx_mali_sym("glUniform2fv");
    fn(location, count, value);
}
GL_APICALL void GL_APIENTRY glUniform2i(GLint location, GLint v0, GLint v1) {
    static void (*fn)(GLint location, GLint v0, GLint v1);
    if (!fn) fn = nx_mali_sym("glUniform2i");
    fn(location, v0, v1);
}
GL_APICALL void GL_APIENTRY glUniform2iv(GLint location, GLsizei count, const GLint *value) {
    static void (*fn)(GLint location, GLsizei count, const GLint *value);
    if (!fn) fn = nx_mali_sym("glUniform2iv");
    fn(location, count, value);
}
GL_APICALL void GL_APIENTRY glUniform2ui(GLint location, GLuint v0, GLuint v1) {
    NX_STUB_LOG("glUniform2ui");
    (void)location;
    (void)v0;
    (void)v1;
}
GL_APICALL void GL_APIENTRY glUniform2uiv(GLint location, GLsizei count, const GLuint *value) {
    NX_STUB_LOG("glUniform2uiv");
    (void)location;
    (void)count;
    (void)value;
}
GL_APICALL void GL_APIENTRY glUniform3f(GLint location, GLfloat v0, GLfloat v1, GLfloat v2) {
    static void (*fn)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
    if (!fn) fn = nx_mali_sym("glUniform3f");
    fn(location, v0, v1, v2);
}
GL_APICALL void GL_APIENTRY glUniform3fv(GLint location, GLsizei count, const GLfloat *value) {
    static void (*fn)(GLint location, GLsizei count, const GLfloat *value);
    if (!fn) fn = nx_mali_sym("glUniform3fv");
    fn(location, count, value);
}
GL_APICALL void GL_APIENTRY glUniform3i(GLint location, GLint v0, GLint v1, GLint v2) {
    static void (*fn)(GLint location, GLint v0, GLint v1, GLint v2);
    if (!fn) fn = nx_mali_sym("glUniform3i");
    fn(location, v0, v1, v2);
}
GL_APICALL void GL_APIENTRY glUniform3iv(GLint location, GLsizei count, const GLint *value) {
    static void (*fn)(GLint location, GLsizei count, const GLint *value);
    if (!fn) fn = nx_mali_sym("glUniform3iv");
    fn(location, count, value);
}
GL_APICALL void GL_APIENTRY glUniform3ui(GLint location, GLuint v0, GLuint v1, GLuint v2) {
    NX_STUB_LOG("glUniform3ui");
    (void)location;
    (void)v0;
    (void)v1;
    (void)v2;
}
GL_APICALL void GL_APIENTRY glUniform3uiv(GLint location, GLsizei count, const GLuint *value) {
    NX_STUB_LOG("glUniform3uiv");
    (void)location;
    (void)count;
    (void)value;
}
GL_APICALL void GL_APIENTRY glUniform4f(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3) {
    static void (*fn)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
    if (!fn) fn = nx_mali_sym("glUniform4f");
    fn(location, v0, v1, v2, v3);
}
GL_APICALL void GL_APIENTRY glUniform4fv(GLint location, GLsizei count, const GLfloat *value) {
    static void (*fn)(GLint location, GLsizei count, const GLfloat *value);
    if (!fn) fn = nx_mali_sym("glUniform4fv");
    fn(location, count, value);
}
GL_APICALL void GL_APIENTRY glUniform4i(GLint location, GLint v0, GLint v1, GLint v2, GLint v3) {
    static void (*fn)(GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
    if (!fn) fn = nx_mali_sym("glUniform4i");
    fn(location, v0, v1, v2, v3);
}
GL_APICALL void GL_APIENTRY glUniform4iv(GLint location, GLsizei count, const GLint *value) {
    static void (*fn)(GLint location, GLsizei count, const GLint *value);
    if (!fn) fn = nx_mali_sym("glUniform4iv");
    fn(location, count, value);
}
GL_APICALL void GL_APIENTRY glUniform4ui(GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3) {
    NX_STUB_LOG("glUniform4ui");
    (void)location;
    (void)v0;
    (void)v1;
    (void)v2;
    (void)v3;
}
GL_APICALL void GL_APIENTRY glUniform4uiv(GLint location, GLsizei count, const GLuint *value) {
    NX_STUB_LOG("glUniform4uiv");
    (void)location;
    (void)count;
    (void)value;
}
GL_APICALL void GL_APIENTRY glUniformMatrix2fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) {
    static void (*fn)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
    if (!fn) fn = nx_mali_sym("glUniformMatrix2fv");
    fn(location, count, transpose, value);
}
GL_APICALL void GL_APIENTRY glUniformMatrix2x3fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) {
    NX_STUB_LOG("glUniformMatrix2x3fv");
    (void)location;
    (void)count;
    (void)transpose;
    (void)value;
}
GL_APICALL void GL_APIENTRY glUniformMatrix2x4fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) {
    NX_STUB_LOG("glUniformMatrix2x4fv");
    (void)location;
    (void)count;
    (void)transpose;
    (void)value;
}
GL_APICALL void GL_APIENTRY glUniformMatrix3fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) {
    static void (*fn)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
    if (!fn) fn = nx_mali_sym("glUniformMatrix3fv");
    fn(location, count, transpose, value);
}
GL_APICALL void GL_APIENTRY glUniformMatrix3x2fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) {
    NX_STUB_LOG("glUniformMatrix3x2fv");
    (void)location;
    (void)count;
    (void)transpose;
    (void)value;
}
GL_APICALL void GL_APIENTRY glUniformMatrix3x4fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) {
    NX_STUB_LOG("glUniformMatrix3x4fv");
    (void)location;
    (void)count;
    (void)transpose;
    (void)value;
}
GL_APICALL void GL_APIENTRY glUniformMatrix4fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) {
    static void (*fn)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
    if (!fn) fn = nx_mali_sym("glUniformMatrix4fv");
    fn(location, count, transpose, value);
}
GL_APICALL void GL_APIENTRY glUniformMatrix4x2fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) {
    NX_STUB_LOG("glUniformMatrix4x2fv");
    (void)location;
    (void)count;
    (void)transpose;
    (void)value;
}
GL_APICALL void GL_APIENTRY glUniformMatrix4x3fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) {
    NX_STUB_LOG("glUniformMatrix4x3fv");
    (void)location;
    (void)count;
    (void)transpose;
    (void)value;
}
GL_APICALL void GL_APIENTRY glValidateProgram(GLuint program) {
    static void (*fn)(GLuint program);
    if (!fn) fn = nx_mali_sym("glValidateProgram");
    fn(program);
}
GL_APICALL void GL_APIENTRY glVertexAttrib1f(GLuint index, GLfloat x) {
    static void (*fn)(GLuint index, GLfloat x);
    if (!fn) fn = nx_mali_sym("glVertexAttrib1f");
    fn(index, x);
}
GL_APICALL void GL_APIENTRY glVertexAttrib1fv(GLuint index, const GLfloat *v) {
    static void (*fn)(GLuint index, const GLfloat *v);
    if (!fn) fn = nx_mali_sym("glVertexAttrib1fv");
    fn(index, v);
}
GL_APICALL void GL_APIENTRY glVertexAttrib2f(GLuint index, GLfloat x, GLfloat y) {
    static void (*fn)(GLuint index, GLfloat x, GLfloat y);
    if (!fn) fn = nx_mali_sym("glVertexAttrib2f");
    fn(index, x, y);
}
GL_APICALL void GL_APIENTRY glVertexAttrib2fv(GLuint index, const GLfloat *v) {
    static void (*fn)(GLuint index, const GLfloat *v);
    if (!fn) fn = nx_mali_sym("glVertexAttrib2fv");
    fn(index, v);
}
GL_APICALL void GL_APIENTRY glVertexAttrib3f(GLuint index, GLfloat x, GLfloat y, GLfloat z) {
    static void (*fn)(GLuint index, GLfloat x, GLfloat y, GLfloat z);
    if (!fn) fn = nx_mali_sym("glVertexAttrib3f");
    fn(index, x, y, z);
}
GL_APICALL void GL_APIENTRY glVertexAttrib3fv(GLuint index, const GLfloat *v) {
    static void (*fn)(GLuint index, const GLfloat *v);
    if (!fn) fn = nx_mali_sym("glVertexAttrib3fv");
    fn(index, v);
}
GL_APICALL void GL_APIENTRY glVertexAttrib4f(GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w) {
    static void (*fn)(GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
    if (!fn) fn = nx_mali_sym("glVertexAttrib4f");
    fn(index, x, y, z, w);
}
GL_APICALL void GL_APIENTRY glVertexAttrib4fv(GLuint index, const GLfloat *v) {
    static void (*fn)(GLuint index, const GLfloat *v);
    if (!fn) fn = nx_mali_sym("glVertexAttrib4fv");
    fn(index, v);
}
GL_APICALL void GL_APIENTRY glVertexAttribI4i(GLuint index, GLint x, GLint y, GLint z, GLint w) {
    NX_STUB_LOG("glVertexAttribI4i");
    (void)index;
    (void)x;
    (void)y;
    (void)z;
    (void)w;
}
GL_APICALL void GL_APIENTRY glVertexAttribI4iv(GLuint index, const GLint *v) {
    NX_STUB_LOG("glVertexAttribI4iv");
    (void)index;
    (void)v;
}
GL_APICALL void GL_APIENTRY glVertexAttribI4ui(GLuint index, GLuint x, GLuint y, GLuint z, GLuint w) {
    NX_STUB_LOG("glVertexAttribI4ui");
    (void)index;
    (void)x;
    (void)y;
    (void)z;
    (void)w;
}
GL_APICALL void GL_APIENTRY glVertexAttribI4uiv(GLuint index, const GLuint *v) {
    NX_STUB_LOG("glVertexAttribI4uiv");
    (void)index;
    (void)v;
}
